In [1]:
import pandas as pd
import numpy as np

In [2]:
na_vals = ['NA', 'Missing ']
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent', na_values=na_vals)
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='Column')

In [3]:
df.shape # shape of the dataframe

(88883, 84)

In [4]:
df.info()  # lists all columns and their data type, object usually means string in Pandas

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88883 entries, 1 to 88863
Data columns (total 84 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MainBranch              88331 non-null  object
 1   Hobbyist                88883 non-null  object
 2   OpenSourcer             88883 non-null  object
 3   OpenSource              86842 non-null  object
 4   Employment              87181 non-null  object
 5   Country                 88751 non-null  object
 6   Student                 87014 non-null  object
 7   EdLevel                 86390 non-null  object
 8   UndergradMajor          75614 non-null  object
 9   EduOther                84260 non-null  object
 10  OrgSize                 71791 non-null  object
 11  DevType                 81335 non-null  object
 12  YearsCode               87938 non-null  object
 13  Age1stCode              87634 non-null  object
 14  YearsCodePro            74331 non-null  object
 15  CareerSat               72847 non-null  object
 16  JobSat                  70988 non-null  object
 17  MgrIdiot                61159 non-null  object
 18  MgrMoney                61157 non-null  object
 19  MgrWant                 61232 non-null  object
 20  JobSeek                 80555 non-null  object
 21  LastHireDate            79854 non-null  object
 22  LastInt                 67155 non-null  object
 23  FizzBuzz                71344 non-null  object
 24  JobFactors              79371 non-null  object
 25  ResumeUpdate            77877 non-null  object
 26  CurrencySymbol          71392 non-null  object
 27  CurrencyDesc            71392 non-null  object
 28  CompTotal               55945 non-null  float64
 29  CompFreq                63268 non-null  object
 30  ConvertedComp           55823 non-null  float64
 31  WorkWeekHrs             64503 non-null  float64
 32  WorkPlan                68914 non-null  object
 33  WorkChallenge           68141 non-null  object
 34  WorkRemote              70284 non-null  object
 35  WorkLoc                 70055 non-null  object
 36  ImpSyn                  71779 non-null  object
 37  CodeRev                 70390 non-null  object
 38  CodeRevHrs              49790 non-null  float64
 39  UnitTests               62668 non-null  object
 40  PurchaseHow             61108 non-null  object
 41  PurchaseWhat            62029 non-null  object
 42  LanguageWorkedWith      87569 non-null  object
 43  LanguageDesireNextYear  84088 non-null  object
 44  DatabaseWorkedWith      76026 non-null  object
 45  DatabaseDesireNextYear  69147 non-null  object
 46  PlatformWorkedWith      80714 non-null  object
 47  PlatformDesireNextYear  77443 non-null  object
 48  WebFrameWorkedWith      65022 non-null  object
 49  WebFrameDesireNextYear  62944 non-null  object
 50  MiscTechWorkedWith      59586 non-null  object
 51  MiscTechDesireNextYear  64511 non-null  object
 52  DevEnviron              87317 non-null  object
 53  OpSys                   87851 non-null  object
 54  Containers              85366 non-null  object
 55  BlockchainOrg           48175 non-null  object
 56  BlockchainIs            60165 non-null  object
 57  BetterLife              86269 non-null  object
 58  ITperson                87141 non-null  object
 59  OffOn                   86663 non-null  object
 60  SocialMedia             84437 non-null  object
 61  Extraversion            87305 non-null  object
 62  ScreenName              80486 non-null  object
 63  SOVisit1st              83877 non-null  object
 64  SOVisitFreq             88263 non-null  object
 65  SOVisitTo               88086 non-null  object
 66  SOFindAnswer            87816 non-null  object
 67  SOTimeSaved             86344 non-null  object
 68  SOHowMuchTime           68378 non-null  object
 69  SOAccount               87828 non-null  object
 70  SOPartFreq              74692 non-null  object
 71  SOJobs                  88066 non-null  object
 72  EntTeams                87841 non-null  object
 73  SOComm                  88131 non-null  object
 74  WelcomeChange           85855 non-null  object
 75  SONewContent            69560 non-null  object
 76  Age                     79210 non-null  float64
 77  Gender                  85406 non-null  object
 78  Trans                   83607 non-null  object
 79  Sexuality               76147 non-null  object
 80  Ethnicity               76668 non-null  object
 81  Dependents              83059 non-null  object
 82  SurveyLength            86984 non-null  object
 83  SurveyEase              87081 non-null  object
dtypes: float64(5), object(79)
memory usage: 57.6+ MB

In [5]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [6]:
df.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [7]:
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [8]:
# how a pandas dataframe works
# you can consider each key as a column name and each of ith items of lists as a row

people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Deer"],
    "email": ["corey@gmail.com","jane@gmail.com", "JohnDoe@gmail.com"]
}

In [9]:
people_df = pd.DataFrame(people)
people_df

   first     last              email
0  Corey  Schafer    corey@gmail.com
1   Jane      Doe     jane@gmail.com
2   John     Deer  JohnDoe@gmail.com

In [10]:
type(people_df['email'])  # series can be looked as rows of a column, like a list in python

pandas.core.series.Series

In [11]:
people_df.email  # same as df['email']

0      corey@gmail.com
1       jane@gmail.com
2    JohnDoe@gmail.com
Name: email, dtype: object

In [12]:
people_df[['last', 'email']]

      last              email
0  Schafer    corey@gmail.com
1      Doe     jane@gmail.com
2     Deer  JohnDoe@gmail.com

In [13]:
people_df.columns

Index(['first', 'last', 'email'], dtype='object')

In [14]:
people_df.iloc[0] # integer lookup, first column

first              Corey
last             Schafer
email    corey@gmail.com
Name: 0, dtype: object

In [15]:
people_df.iloc[[0, 1], 2]

0    corey@gmail.com
1     jane@gmail.com
Name: email, dtype: object

In [16]:
people_df.loc[0]  # first row

first              Corey
last             Schafer
email    corey@gmail.com
Name: 0, dtype: object

In [17]:
people_df.loc[[0, 1], ['email', 'last']]

             email     last
0  corey@gmail.com  Schafer
1   jane@gmail.com      Doe

In [18]:
df['DatabaseDesireNextYear'].value_counts()

PostgreSQL                                                                          3539
Microsoft SQL Server                                                                3290
MySQL                                                                               3184
MongoDB                                                                             2250
SQLite                                                                              1506
                                                                                    ...
Elasticsearch;Firebase;Microsoft SQL Server;MySQL;Oracle;PostgreSQL;Redis;SQLite       1
Microsoft SQL Server;PostgreSQL;Redis;SQLite;Other(s):                                 1
Couchbase;MariaDB;MongoDB;MySQL;PostgreSQL;Redis                                       1
Cassandra;Elasticsearch;Firebase;Microsoft SQL Server;MySQL;Oracle;Redis;SQLite        1
MongoDB;Microsoft SQL Server;MySQL;PostgreSQL;SQLite;Other(s):                         1
Name: DatabaseDesireNextYear, Length: 3923, dtype: int64

In [19]:
df.loc[[1, 2, 3], ['Hobbyist', 'DatabaseDesireNextYear']]

           Hobbyist DatabaseDesireNextYear
Respondent
1               Yes                  MySQL
2                No                  MySQL
3               Yes             PostgreSQL

In [20]:
df.loc[1:4, ['Hobbyist', 'DatabaseDesireNextYear']]  # slicing in pandas is inclusive

           Hobbyist DatabaseDesireNextYear
Respondent
1               Yes                  MySQL
2                No                  MySQL
3               Yes             PostgreSQL
4                No           MySQL;SQLite

In [21]:
df.loc[1:2, 'Hobbyist':'Employment']

,Hobbyist,OpenSourcer,OpenSource,Employment
Respondent,,,,
1,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
2,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"

In [22]:
people_df.set_index('email')  # set a column as index of dataframe

                   first     last
email
corey@gmail.com    Corey  Schafer
jane@gmail.com      Jane      Doe
JohnDoe@gmail.com   John     Deer

In [23]:
people_df.set_index('email', inplace=True)  # applies changes to the current dataframe

In [24]:
people_df.reset_index(inplace=True)
people_df

               email  first     last
0    corey@gmail.com  Corey  Schafer
1     jane@gmail.com   Jane      Doe
2  JohnDoe@gmail.com   John     Deer

In [25]:
# schema_df.loc[['MgrIdiot', 'WorkChallenge']]
schema_df.columns

Index(['Column', 'QuestionText'], dtype='object')

In [26]:
schema_df.sort_index(ascending=False) # sort alphabetically from Z to A, default is True

                    Column                                       QuestionText
84              SurveyEase  How easy or difficult was this survey to compl...
83            SurveyLength  How do you feel about the length of the survey...
82              Dependents  Do you have any dependents (e.g., children, el...
81               Ethnicity  Which of the following do you identify as? Ple...
80               Sexuality  Which of the following do you currently identi...
79                   Trans                    Do you identify as transgender?
78                  Gender  Which of the following do you currently identi...
77                     Age  What is your age (in years)? If you prefer not...
76            SONewContent  Would you like to see any of the following on ...
75           WelcomeChange  Compared to last year, how welcome do you feel...
74                  SOComm  Do you consider yourself a member of the Stack...
73                EntTeams  Have you ever used Stack Overflow for Enterpri...
72                  SOJobs  Have you ever used or visited Stack Overflow J...
71              SOPartFreq  How frequently would you say you participate i...
70               SOAccount              Do you have a Stack Overflow account?
69           SOHowMuchTime  About how much time did you save? If you're no...
68             SOTimeSaved  Think back to the last time you solved a codin...
67            SOFindAnswer  On average, how many times a week do you find ...
66               SOVisitTo  I visit Stack Overflow to... (check all that a...
65             SOVisitFreq  How frequently would you say you visit Stack O...
64              SOVisit1st  To the best of your memory, when did you first...
63              ScreenName                               What do you call it?
62            Extraversion    Do you prefer online chat or IRL conversations?
61             SocialMedia        What social media site do you use the most?
60                   OffOn        Have you tried turning it off and on again?
59                ITperson   Are you the "IT support person" for your family?
58              BetterLife  Do you think people born today will have a bet...
57            BlockchainIs  Blockchain / cryptocurrency technology is prim...
56           BlockchainOrg  How is your organization thinking about or imp...
55              Containers  How do you use containers (Docker, Open Contai...
54                   OpSys  What is the primary operating system in which ...
53              DevEnviron  Which development environment(s) do you use re...
52  MiscTechDesireNextYear  Which of the following other frameworks, libra...
51      MiscTechWorkedWith  Which of the following other frameworks, libra...
50  WebFrameDesireNextYear  Which of the following web frameworks have you...
49      WebFrameWorkedWith  Which of the following web frameworks have you...
48  PlatformDesireNextYear  Which of the following platforms have you done...
47      PlatformWorkedWith  Which of the following platforms have you done...
46  DatabaseDesireNextYear  Which of the following database environments h...
45      DatabaseWorkedWith  Which of the following database environments h...
44  LanguageDesireNextYear  Which of the following programming, scripting,...
43      LanguageWorkedWith  Which of the following programming, scripting,...
42            PurchaseWhat  What level of influence do you, personally, ha...
41             PurchaseHow  How does your company make decisions about pur...
40               UnitTests  Does your company regularly employ unit tests ...
39              CodeRevHrs  On average, how many hours per week do you spe...
38                 CodeRev           Do you review code as part of your work?
37                  ImpSyn  For the specific work you do, and the years of...
36                 WorkLoc                    Where would you prefer to work?
35              WorkRemote                    How often do you work remotely?
34           WorkChallenge  Of these options, what are your greatest chall...
33                WorkPlan            How structured or planned is your work?
32             WorkWeekHrs   On average, how many hours per week do you work?
31           ConvertedComp  Salary converted to annual USD salaries using ...
30                CompFreq   Is that compensation weekly, monthly, or yearly?
29               CompTotal  What is your current total compensation (salar...
28            CurrencyDesc  Which currency do you use day-to-day? If your ...
27          CurrencySymbol  Which currency do you use day-to-day? If your ...
26            ResumeUpdate  Think back to the last time you updated your r...
25              JobFactors  Imagine that you are deciding between two job ...
24                FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
23                 LastInt  In your most recent successful job interview (...
22            LastHireDate  When was the last time that you took a job wit...
21                 JobSeek  Which of the following best describes your cur...
20                 MgrWant  Do you want to become a manager yourself in th...
19                MgrMoney  Do you believe that you need to be a manager t...
18                MgrIdiot  How confident are you that your manager knows ...
17                  JobSat  How satisfied are you with your current job? (...
16               CareerSat  Overall, how satisfied are you with your caree...
15            YearsCodePro  How many years have you coded professionally (...
14              Age1stCode  At what age did you write your first line of c...
13               YearsCode  Including any education, how many years have y...
12                 DevType  Which of the following describe you? Please se...
11                 OrgSize  Approximately how many people are employed by ...
10                EduOther  Which of the following types of non-degree edu...
9           UndergradMajor  What was your main or most important field of ...
8                  EdLevel  Which of the following best describes the high...
7                  Student  Are you currently enrolled in a formal, degree...
6                  Country          In which country do you currently reside?
5               Employment  Which of the following best describes your cur...
4               OpenSource  How do you feel about the quality of open sour...
3              OpenSourcer        How often do you contribute to open source?
2                 Hobbyist                            Do you code as a hobby?
1               MainBranch  Which of the following options best describes ...
0               Respondent  Randomized respondent ID number (not in order ...

In [27]:
filt = (people_df['last'] == 'Doe')  # returns a series with True/False
filt

0    False
1     True
2    False
Name: last, dtype: bool

In [28]:
people_df[filt]   # can also be people_df[people_df['last'] == 'Doe']

            email first last
1  jane@gmail.com  Jane  Doe

In [29]:
people_df.loc[filt, 'email']   # .loc[rows, columns]

1    jane@gmail.com
Name: email, dtype: object

In [30]:
# & : and   | : or
people_df.loc[(people_df['last'] == 'Doe') & (people_df['first'] == 'Jane') ]

            email first last
1  jane@gmail.com  Jane  Doe

In [31]:
people_df.loc[~filt, 'email'] # ~ is same as !=

0      corey@gmail.com
2    JohnDoe@gmail.com
Name: email, dtype: object

In [32]:
high_salary = (df['ConvertedComp'] > 70000)

In [33]:
df.loc[high_salary, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
9,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
16,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88879,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88882,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [34]:
countries = ['United States', 'India', 'United Kingdom', 'Germany', 'Canada']
filt = df['Country'].isin(countries)

df.loc[filt, 'Country']

Respondent
1        United Kingdom
4         United States
6                Canada
8                 India
10                India
              ...
85642     United States
85961    United Kingdom
86012             India
88282     United States
88377            Canada
Name: Country, Length: 45008, dtype: object

In [35]:
filt = df['LanguageWorkedWith'].str.contains('Swift', na=False)
df.loc[filt, 'LanguageWorkedWith']

Respondent
21       Assembly;Bash/Shell/PowerShell;C;C++;Go;Java;J...
26       Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...
90       Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
115         Assembly;C#;HTML/CSS;Java;JavaScript;SQL;Swift
152      HTML/CSS;Java;JavaScript;Kotlin;Objective-C;Py...
                               ...
72325                     HTML/CSS;JavaScript;Python;Swift
75974    Go;HTML/CSS;Java;JavaScript;Kotlin;Python;Swif...
78741    Assembly;Bash/Shell/PowerShell;C;C++;C#;Clojur...
84299     HTML/CSS;Java;JavaScript;Python;Swift;TypeScript
88863    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
Name: LanguageWorkedWith, Length: 5744, dtype: object

In [36]:
people_df.columns

Index(['email', 'first', 'last'], dtype='object')

In [37]:
people_df.columns = ['email', 'first_name', 'last_name']
people_df

               email first_name last_name
0    corey@gmail.com      Corey   Schafer
1     jane@gmail.com       Jane       Doe
2  JohnDoe@gmail.com       John      Deer

In [38]:
people_df.columns = [x.lower() for x in people_df.columns]
people_df

               email first_name last_name
0    corey@gmail.com      Corey   Schafer
1     jane@gmail.com       Jane       Doe
2  JohnDoe@gmail.com       John      Deer

In [39]:
people_df.columns = people_df.columns.str.replace(' ', '_') # if there is space in column names, change them to _

In [40]:
# only change specific columns
people_df.rename(columns={'first_name': 'First', 'last_name': 'Last'}, inplace=True)

people_df

               email  First     Last
0    corey@gmail.com  Corey  Schafer
1     jane@gmail.com   Jane      Doe
2  JohnDoe@gmail.com   John     Deer

In [41]:
people_df.loc[2] = ['JohnSmith@gmail.com', 'John', 'Smith']  # change/update a row
people_df

                 email  First     Last
0      corey@gmail.com  Corey  Schafer
1       jane@gmail.com   Jane      Doe
2  JohnSmith@gmail.com   John    Smith

In [42]:
people_df.loc[2, 'Last'] = 'Jones'  # update specific column at specific row
people_df

# people_df[filt]['Last'] = 'Jones'    *this will return an error

                 email  First     Last
0      corey@gmail.com  Corey  Schafer
1       jane@gmail.com   Jane      Doe
2  JohnSmith@gmail.com   John    Jones

In [43]:
people_df.at[2, 'Last'] = 'Doe' # update specific column at specific row
people_df

                 email  First     Last
0      corey@gmail.com  Corey  Schafer
1       jane@gmail.com   Jane      Doe
2  JohnSmith@gmail.com   John      Doe

In [44]:
filt = (people_df['email'] == 'JohnSmith@gmail.com')
people_df[filt]['Last']

2    Doe
Name: Last, dtype: object

In [45]:
people_df['email'] = people_df['email'].str.upper()  # how to make the upperCase change permanant on dataFrame

people_df

                 email  First     Last
0      COREY@GMAIL.COM  Corey  Schafer
1       JANE@GMAIL.COM   Jane      Doe
2  JOHNSMITH@GMAIL.COM   John      Doe

In [46]:
people_df['email'].apply(len)

0    15
1    14
2    19
Name: email, dtype: int64

In [47]:
def update_email(email):
    return email.lower()

people_df['email'] = people_df['email'].apply(update_email)
people_df

                 email  First     Last
0      corey@gmail.com  Corey  Schafer
1       jane@gmail.com   Jane      Doe
2  johnsmith@gmail.com   John      Doe

In [48]:
people_df['First'] = people_df['First'].apply(lambda x: x.upper())
people_df

                 email  First     Last
0      corey@gmail.com  COREY  Schafer
1       jane@gmail.com   JANE      Doe
2  johnsmith@gmail.com   JOHN      Doe

In [49]:
people_df.apply(len)  # number of rows for each column

email    3
First    3
Last     3
dtype: int64

In [50]:
len(people_df['email'])

3

In [51]:
people_df.apply(len, axis='columns')  # number of columns for each row

0    3
1    3
2    3
dtype: int64

In [52]:
people_df.apply(pd.Series.min)  # get smallest values for each column

email    corey@gmail.com
First              COREY
Last                 Doe
dtype: object

In [53]:
people_df.applymap(len)   # applies len() function to each cell in the dataFrame

   email  First  Last
0     15      5     7
1     14      4     3
2     19      4     3

In [54]:
people_df.applymap(str.lower)  # this will return error if we had numerical values here

                 email  First     Last
0      corey@gmail.com  corey  schafer
1       jane@gmail.com   jane      doe
2  johnsmith@gmail.com   john      doe

In [55]:
people_df['First'] = people _df['First'].replace('corey', 'Bob')
people_df

SyntaxError: invalid syntax (<ipython-input-55-945de171f21e>, line 1)

In [56]:
df.rename(columns={'ConvertedComp': 'SalaryUSD'}, inplace=True)  # rename column

In [57]:
df['SalaryUSD']

Respondent
1            NaN
2            NaN
3         8820.0
4        61000.0
5            NaN
          ...
88377        NaN
88601        NaN
88802        NaN
88816        NaN
88863        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [58]:
df['Hobbyist'].map({'Yes': True, 'No': False})

Respondent
1         True
2        False
3         True
4        False
5         True
         ...
88377     True
88601    False
88802    False
88816    False
88863     True
Name: Hobbyist, Length: 88883, dtype: bool

In [59]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes': True, 'No': False})  # anything outside Yes/No will be NaN

In [60]:
people_df['First'] + ' ' + people_df['Last']

0    COREY Schafer
1         JANE Doe
2         JOHN Doe
dtype: object

In [61]:
people_df['full_name'] = people_df['First'] + ' ' + people_df['Last']

In [62]:
people_df

                 email  First     Last      full_name
0      corey@gmail.com  COREY  Schafer  COREY Schafer
1       jane@gmail.com   JANE      Doe       JANE Doe
2  johnsmith@gmail.com   JOHN      Doe       JOHN Doe

In [63]:
people_df.drop(columns=['First', 'Last'], inplace=True) # will throw an error if the column names are spelled wrong

In [64]:
people_df

                 email      full_name
0      corey@gmail.com  COREY Schafer
1       jane@gmail.com       JANE Doe
2  johnsmith@gmail.com       JOHN Doe

In [65]:
people_df[['first', 'last']] = people_df['full_name'].str.split(' ', expand=True)
people_df.drop(columns=['full_name'], inplace=True)
people_df

                 email  first     last
0      corey@gmail.com  COREY  Schafer
1       jane@gmail.com   JANE      Doe
2  johnsmith@gmail.com   JOHN      Doe

In [66]:
people_df.append({'first': 'Tony'}, ignore_index=True)  # adding rows to dataframe

                 email  first     last
0      corey@gmail.com  COREY  Schafer
1       jane@gmail.com   JANE      Doe
2  johnsmith@gmail.com   JOHN      Doe
3                  NaN   Tony      NaN

In [67]:
people = {
    "first": ["dude", "duddete"],
    "last": ["one", "two"],
    "email": ["dude@gmail.com","duddete@gmail.com"]
}

people_df2 = pd.DataFrame(people)
people_df2

     first last              email
0     dude  one     dude@gmail.com
1  duddete  two  duddete@gmail.com

In [68]:
people_df = people_df.append(people_df2, ignore_index=True)  # append dataframes together
people_df

                 email    first     last
0      corey@gmail.com    COREY  Schafer
1       jane@gmail.com     JANE      Doe
2  johnsmith@gmail.com     JOHN      Doe
3       dude@gmail.com     dude      one
4    duddete@gmail.com  duddete      two

In [69]:
people_df.drop(index=4)   # drop rows

                 email  first     last
0      corey@gmail.com  COREY  Schafer
1       jane@gmail.com   JANE      Doe
2  johnsmith@gmail.com   JOHN      Doe
3       dude@gmail.com   dude      one

In [70]:
cond = (people_df['last'] == 'one')

people_df.drop(index=people_df[cond].index)

                 email    first     last
0      corey@gmail.com    COREY  Schafer
1       jane@gmail.com     JANE      Doe
2  johnsmith@gmail.com     JOHN      Doe
4    duddete@gmail.com  duddete      two

In [71]:
people_df.sort_values(by='last', ascending=False)  # sort by column

                 email    first     last
4    duddete@gmail.com  duddete      two
3       dude@gmail.com     dude      one
0      corey@gmail.com    COREY  Schafer
1       jane@gmail.com     JANE      Doe
2  johnsmith@gmail.com     JOHN      Doe

In [72]:
people_df.sort_values(by=['last', 'first'], ascending=False) # sort by several columns

                 email    first     last
4    duddete@gmail.com  duddete      two
3       dude@gmail.com     dude      one
0      corey@gmail.com    COREY  Schafer
2  johnsmith@gmail.com     JOHN      Doe
1       jane@gmail.com     JANE      Doe

In [73]:
 people_df.sort_index() # sort by index

                 email    first     last
0      corey@gmail.com    COREY  Schafer
1       jane@gmail.com     JANE      Doe
2  johnsmith@gmail.com     JOHN      Doe
3       dude@gmail.com     dude      one
4    duddete@gmail.com  duddete      two

In [74]:
df.sort_values(by=['Country', 'SalaryUSD'], ascending=[True, False], inplace=True)
df[['Country', 'SalaryUSD']].head(10)

                Country  SalaryUSD
Respondent
63129       Afghanistan  1000000.0
50499       Afghanistan   153216.0
39258       Afghanistan    19152.0
58450       Afghanistan    17556.0
7085        Afghanistan    14364.0
22450       Afghanistan     7980.0
48436       Afghanistan     4464.0
10746       Afghanistan     3996.0
8149        Afghanistan     1596.0
29736       Afghanistan     1116.0

In [75]:
df['SalaryUSD'].nlargest(10)

Respondent
25983    2000000.0
87896    2000000.0
22013    2000000.0
28243    2000000.0
72732    2000000.0
78151    2000000.0
80200    2000000.0
52132    2000000.0
75561    2000000.0
32250    2000000.0
Name: SalaryUSD, dtype: float64

In [76]:
df.nlargest(3, 'SalaryUSD')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
25983,I am a developer by profession,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, full-stack",8,16,2,Very satisfied,Very satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,Solve a brain-teaser style puzzle;Interview wi...,No,Remote work options;Opportunities for professi...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,65500.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,A few days each month,Office,Average,"Yes, because I see value in code review",2.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,Bash/Shell/PowerShell;C#;F#;Python;SQL;TypeScript,Microsoft SQL Server;MySQL,Microsoft SQL Server;MySQL,AWS;Docker;Heroku;Linux;MacOS;Raspberry Pi;Win...,AWS;Docker;Linux;MacOS;Windows,Angular/Angular.js,Angular/Angular.js;Flask;React.js,.NET;.NET Core;Node.js,.NET Core;Node.js,Notepad++;Sublime Text;Vim;Visual Studio;Visua...,Windows,Development;Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,Yes,Reddit,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87896,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, full-stack",9,17,8,Very satisfied,Very satisfied,Somewhat confident,No,I am already a manager,I am not interested in new job opportunities,More than 4 years ago,Write any code;Interview with people in senior...,No,Office environment or company culture;Diversit...,"Something else changed (education, award, medi...",USD,United States dollar,55000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",3.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,HTML/CSS;JavaScript;PHP;SQL,HTML/CSS;JavaScript;PHP;Ruby;SQL;TypeScript,MariaDB;MySQL;PostgreSQL,MariaDB;MySQL;PostgreSQL,WordPress,NaN,jQuery;Laravel;Vue.js,Express;Laravel;Ruby on Rails;Vue.js,NaN,Node.js,Sublime Text;Vim;Visual Studio Code,Linux-based,I do not use containers,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,Twitter,Online,Handle,2011,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
22013,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,2-9 employees,Academic researcher;Data scientist or machine ...,3,26,3,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,1500000.0,Weekly,2000000.0,50.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Home,A little below average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have a great deal of influence,Assembly;Bash/Shell/PowerShell;C;C++;Java;Java...,Python;Swift,Cassandra;Microsoft SQL Server;Oracle,Cassandra,Android;Arduino;Google Cloud Platform;IBM Clou...,IBM Cloud or Watson;Windows,jQuery,NaN,TensorFlow,TensorFlow,Visual Studio;Visual Studio Code,Windows,Development,Implementing our own cryptocurrency,Useful across many domains and could change ma...,Yes,Yes,No,YouTube,Online,Screen Name,NaN,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy

In [77]:
# aggregation: mean | median | mode
df['SalaryUSD'].median()

57287.0

In [78]:
df.median()  # only shows numerical values

Hobbyist           1.0
CompTotal      62000.0
SalaryUSD      57287.0
WorkWeekHrs       40.0
CodeRevHrs         4.0
Age               29.0
dtype: float64

In [79]:
df[df['Country'] == 'United States']['SalaryUSD'].median()

110000.0

In [80]:
df[df['Country'] == 'India']['SalaryUSD'].mean()

28057.664916229056

In [81]:
df[df['Country'] == 'South Africa']['SalaryUSD'].median()

38354.0

In [82]:
df.describe()

          CompTotal     SalaryUSD   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04  5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11  1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13  2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00  0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04  2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04  5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05  1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16  2.000000e+06   4850.000000     99.000000     99.000000

In [83]:
df['Hobbyist'].value_counts()

True     71257
False    17626
Name: Hobbyist, dtype: int64

In [84]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [85]:
df['SocialMedia'].value_counts(normalize=True)

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [86]:
df['Country'].value_counts()

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
North Korea                             1
Timor-Leste                             1
Chad                                    1
Saint Vincent and the Grenadines        1
Saint Kitts and Nevis                   1
Name: Country, Length: 179, dtype: int64

In [87]:
country_group = df.groupby(['Country'])  # group dataframe based on country

In [88]:
country_group.get_group('United States')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
58,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,NaN,"Developer, back-end;Developer, desktop or ente...",28,19,23,Very satisfied,Very satisfied,Very confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,NaN,Yes,Office environment or company culture;Remote w...,Re-entry into the workforce,USD,United States dollar,113000.0,Weekly,2000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Non-wor...,"Less than half the time, but at least one day ...",Home,A little above average,"Yes, because I see value in code review",1.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,C#;Java;SQL,C#;F#;Java;Kotlin;SQL,Microsoft SQL Server;Oracle;SQLite,Microsoft SQL Server;Oracle;SQLite,Android;Windows,Android;Raspberry Pi;Windows,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET,Hadoop;.NET;.NET Core;Node.js;Puppet;Xamarin,Android Studio;Visual Studio,Windows,I do not use containers,NaN,NaN,Yes,Yes,Yes,I don't use social media,In real life (in person),Login,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,NaN,Easy
102,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","5,000 to 9,999 employees","Developer, full-stack",8,29,5,Slightly satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,"Something else changed (education, award, medi...",USD,United States dollar,67800.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,Average,No,NaN,"No, but I think we should",Not sure,I have some influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C;C++;Elixir;Go;Ruby;WebAssembly,Microsoft SQL Server,MongoDB;PostgreSQL;SQLite,Microsoft Azure,AWS;Kubernetes;Microsoft Azure,ASP.NET;jQuery;React.js;Other(s):,Angular/Angular.js;Vue.js,.NET;.NET Core,Node.js,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
166,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A social science (ex. anthropology, psychology...",Participated in a full-time developer training...,20 to 99 employees,"Developer, back-end;Developer, front-end;Devel...",7,15,6,Slightly satisfied,Slightly satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",3-4 years ago,Write any code;Complete a take-home project;So...,No,Financial performance or funding status of the...,I had a negative experience or interaction at ...,USD,United States dollar,137000.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Not enough people...,Less than once per month / Never,Home,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;Go;HTML/CSS;Java;JavaScr...,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redi...,PostgreSQL;Redis;SQLite,AWS;Docker;Linux,AWS;Docker;iOS;Kubernetes;Linux,jQuery;React.js;Ruby on Rails,React.js;Ruby on Rails,NaN,NaN,Vim,Linux-based,Development;Testing;Production,Not at all,A passing fad,Yes,SIGH,Yes,Twitter,Online,Username,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",Just as welcome now as I felt last year,NaN,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
436,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Database administrator;Developer, back-end;Dev...",20,18,17,Slightly satisfied,Slightly satisfied,Somewhat confident,Yes,I am already a manager,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,85000.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Meetings;Not e...,A few days each month,Office,Far above average,"Yes, because I see value in code review",NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;P...,Microsoft SQL Server;MySQL;Redis;SQLite,Couchbase;MySQL;Oracle;Redis,Android;AWS;Docker;Google Cloud Platform;Linux...,Android;Arduino;Docker;Google Cloud Platform;L...,jQuery;Laravel;React.js;Vue.js,Laravel;React.js;Vue.js,Node.js,Node.js;React Native;TensorFlow,Android Studio;Atom;Sublime Text;Visual Studio...,Windows,Development;Testing;Production,Not at all,Useful across many domains and could change ma...,Yes,SIGH,Yes,Reddit,Neither,Username,2010,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,38.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
452,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,Employed full-time,United States,"Yes, full-time",I never completed any formal education,NaN,Taken an online course in programming or softw...,100 to 499 employees,"Database administrator;Developer, back-end",7,28,7,Very satisfied,Very satisfied,Very confident,No,No,"I’m not actively looking, but I am open to new...",Less than a year ago,Solve a brain-teaser style puzzle;Interview wi...,No,Specific department or team I'd be working on;...,"Something else changed (education, award, medi...",USD,United States dollar,75000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,A few days each month,Home,Average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,SQL;VBA,Python;SQL,Microsoft SQL Server,MongoDB;Microsoft SQL Server;Oracle;PostgreSQL,Windows,AWS;Linux;Microsoft Azure;Windows,NaN,ASP.NET,.NET,.NET,Notepad++;Visual Studio,Windows,I do not use containers,Not at all,NaN,Yes,"Fortunately, someone else has that title",What?,Facebook,In real life (in person),Screen Name,2013,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,Multiple times per day,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,35.0,Man,No,NaN,White or of European descent,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78292,NaN,False,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A health science (ex. nursing, pharmacy, radio...",Completed an industry certification program (e...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher,42,14,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;Python,Bash/Shell/PowerShell;C;Python,SQLite,SQLite,Linux;Raspberry Pi;Other(s):,Linux;Raspberry Pi;Other(s):,NaN,NaN,Chef,NaN,Emacs;IPython / Jupyter,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),NaN,2013,A few times per week,Find answers to specific questions,Less than once per week,The other resource was slightly faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Somewhat less welcome now than last year,NaN,60.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
82717,NaN,False,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,Less than 1 year,NaN,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android;Windows,Android;Microsoft Azure;Windows,NaN,NaN,NaN,NaN,NaN,MacOS,Testing,NaN,NaN,No,SIGH,Yes,Facebook,In real life (in person),Username,2018,Less than once per month or monthly,Find answers to specific questions,Less than once per week,NaN,60+ minutes,No,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Not sure,NaN,Industry news about technologies you're intere...,44.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
83397,NaN,True,Less than once per year,NaN,"Not employed, but looking for work",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,12,9,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Python;SQL,C;C++;C#;Go;Java;JavaScript;Python;R;Ruby;SQL;...,NaN,NaN,Android;Arduino;Slack,Android;Arduino;Docker;iOS;Raspberry Pi;Slack,Flask,Django;Drupal;Flask;jQuery;React.js,NaN,Chef;Torch/PyTorch,Eclipse;IPython / Jupyter;Sublime Text,MacOS,I do not use containers,NaN,NaN,NaN,SIGH,Yes,NaN,NaN,Handle,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,NaN,27.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
85642,NaN,False,Less than once per year,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",United States,No,Associate degree,"Information systems, information technology, o...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Designer;Marketing or sales professional,20,7,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Go;HTML/CSS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Windows,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,SIGH,Yes,NaN,In real life (in person),Handle,2008,Less than once per month or monthly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,"Non-binary, genderqueer, or gender non-conforming",NaN,Bisexual;Gay or Lesbian,White or of European descent,No,Appropriate in length,Easy
88282,NaN,True,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Developer, desktop or ente...",38,10,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;W...,Bash/Shell/PowerShell;C;Go;HTML/CSS;JavaScript...,NaN,NaN,Linux,Linux;Raspberry Pi,React.js,Vue.js,Node.js,Ansible,Vim,Linux-based,I do not use containers,NaN,An irresponsible use of resources,No,NaN,Yes,I don't use social media,In real life (in person),Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,NaN,No,Too short,Neither easy nor difficult

In [89]:
filt = df['Country'] == 'United States'
custom_df = df.loc[filt]

# difference between code above and groupby is that

In [90]:
df.loc[filt]['SocialMedia'].value_counts()  # value count for social media users in the united states

Reddit                      5700
Twitter                     3468
Facebook                    2844
YouTube                     2463
I don't use social media    1851
Instagram                   1652
LinkedIn                    1020
WhatsApp                     609
Snapchat                     326
WeChat 微信                     93
VK ВКонта́кте                  9
Weibo 新浪微博                     8
Hello                          2
Youku Tudou 优酷                 1
Name: SocialMedia, dtype: int64

In [91]:
country_group['SocialMedia'].value_counts().head(10)  # social media count by the country

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
             LinkedIn                     1
             Twitter                      1
Albania      WhatsApp                    18
             Facebook                    16
             Instagram                   13
Name: SocialMedia, dtype: int64

In [92]:
country_group['SocialMedia'].value_counts().loc['Sweden']

SocialMedia
Reddit                      289
YouTube                     233
Facebook                    214
Twitter                     143
Instagram                   116
I don't use social media     89
WhatsApp                     72
LinkedIn                     53
Snapchat                     21
WeChat 微信                     2
VK ВКонта́кте                 1
Name: SocialMedia, dtype: int64

In [93]:
country_group['SalaryUSD'].median().loc['Sweden']  # since name of country becomes index, we can use .loc here

56004.0

In [94]:
country_group['SalaryUSD'].agg(['median', 'mean']).loc['United States']

median    110000.000000
mean      249546.254589
Name: United States, dtype: float64

In [95]:
filt = (df['Country'] == 'India')  # how many indian programmers know python
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

# .sum() counts True as 1 and False as 0

3105

In [96]:
# here we check how many devs in each country know python
# for groupedby series you can't use aggregation directly, use .apply()
country_group['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [97]:
# total number of devs in each ccountry
country_respondants = df['Country'].value_counts()
# how many devs in each country know python
country_python = country_group['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

python_df = pd.concat([country_respondants, country_python], axis='columns', sort=False) # add dataframes side by side
python_df.rename(columns={'Country': 'NumRespondants', 'LanguageWorkedWith': 'NumKnowsPython'}, inplace=True)
python_df['pctPython'] = (python_df['NumKnowsPython'] / python_df['NumRespondants']) * 100

In [98]:
python_df[python_df['NumRespondants'] > 100].sort_values(by='pctPython', ascending=False)

                                  NumRespondants  NumKnowsPython  pctPython
South Korea                                  160              80  50.000000
Chile                                        206             102  49.514563
Finland                                      546             266  48.717949
Kenya                                        249             120  48.192771
United States                              20949           10083  48.131176
Israel                                       952             457  48.004202
Taiwan                                       187              88  47.058824
Switzerland                                  978             460  47.034765
Hong Kong (S.A.R.)                           188              88  46.808511
Japan                                        391             182  46.547315
Canada                                      3395            1558  45.891016
Singapore                                    303             139  45.874587
New Zealand                                  524             236  45.038168
China                                        664             297  44.728916
France                                      2391            1054  44.081974
Thailand                                     214              92  42.990654
Nepal                                        237             101  42.616034
Estonia                                      195              82  42.051282
Russian Federation                          1694             708  41.794569
Germany                                     5866            2451  41.783157
Ireland                                      501             209  41.716567
United Kingdom                              5737            2384  41.554820
Australia                                   1903             790  41.513400
Netherlands                                 1852             767  41.414687
Belgium                                      727             296  40.715268
Greece                                       556             226  40.647482
Norway                                       574             232  40.418118
Austria                                      839             338  40.286055
Spain                                       1604             641  39.962594
Slovenia                                     298             119  39.932886
Denmark                                      617             246  39.870340
Italy                                       1576             625  39.657360
Brazil                                      1948             767  39.373717
Turkey                                       949             371  39.093783
Poland                                      1922             751  39.073881
Sweden                                      1274             496  38.932496
Slovakia                                     260             101  38.846154
Mexico                                       642             245  38.161994
Czech Republic                               764             285  37.303665
Hungary                                      513             191  37.231969
Sri Lanka                                    372             137  36.827957
Iran                                         738             268  36.314363
Peru                                         130              47  36.153846
Lebanon                                      120              42  35.000000
Portugal                                     525             182  34.666667
Argentina                                    553             191  34.538879
Colombia                                     313             108  34.504792
Egypt                                        323             111  34.365325
India                                       9061            3105  34.267741
Belarus                                      202              69  34.158416
Viet Nam                                     231              78  33.766234
Bangladesh                                   605             204  33.719008
Croatia                                      260              87  33.461538
Romania                                      760             253  33.289474
Uruguay                                      111              36  32.432432
Morocco                                      155              50  32.258065
South Africa                                 627             202  32.216906
Lithuania                                    248              79  31.854839
Malaysia                                     299              95  31.772575
United Arab Emirates                         158              49  31.012658
Tunisia                                      130              40  30.769231
Philippines                                  381             117  30.708661
Algeria                                      134              40  29.850746
Indonesia                                    507             148  29.191321
Nigeria                                      522             152  29.118774
Serbia                                       402             117  29.104478
Latvia                                       136              39  28.676471
Ukraine                                      868             246  28.341014
Bulgaria                                     659             181  27.465857
Other Country (Not Listed Above)             136              37  27.205882
Pakistan                                     923             251  27.193933
Bosnia and Herzegovina                       108              29  26.851852

In [99]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

df_1 = pd.DataFrame(people)

df_1.replace('NA', np.nan, inplace=True)
df_1.replace('Missing', np.nan, inplace=True)

In [100]:
df_1.dropna() # dropna() deletes any line that includes a NaN value

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [101]:
df_1.dropna(axis='index', how='any') 
# if axis is name of any other column, if we had NaN there, it would drop the whole column
# if "how" is set to all, we would only drop columns that have all values missing

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [102]:
df_1.dropna(axis='index', how='all', subset=['email', 'last']) # only drop rows if email AND last name are missing

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
5   None      NaN      Anonymous@email.com  None

In [103]:
df_1.isna()  # returns True if value is considered na

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [104]:
df_1.fillna("MISSING")

     first     last                    email      age
0    Corey  Schafer  CoreyMSchafer@gmail.com       33
1     Jane      Doe        JaneDoe@email.com       55
2     John      Doe        JohnDoe@email.com       63
3    Chris  Schafer                  MISSING       36
4  MISSING  MISSING                  MISSING  MISSING
5  MISSING  MISSING      Anonymous@email.com  MISSING
6  MISSING  MISSING                  MISSING  MISSING

In [105]:
type(np.nan)

float

In [106]:
df_1['age'] = df_1['age'].astype(float)  # if we have missing values, then we can't cast to integer
type(df_1['age'].loc[3])

numpy.float64

In [107]:
df_1['age'].mean()

46.75

In [108]:
df['YearsCode'].unique()

array(['Less than 1 year', '7', '2', '6', '3', '4', '10', '36', '1', nan,
       'More than 50 years', '20', '9', '5', '8', '31', '28', '15', '13',
       '12', '17', '18', '21', '35', '14', '25', '11', '19', '22', '23',
       '40', '39', '30', '43', '27', '33', '29', '24', '34', '16', '32',
       '26', '38', '44', '41', '45', '37', '47', '42', '46', '48', '50',
       '49'], dtype=object)

In [109]:
df['YearsCode'].replace('Less than 1 year', 0, inplace=True)
df['YearsCode'].replace('More than 50 years', 51, inplace=True)

In [110]:
df['YearsCode'] = df['YearsCode'].astype(float)

In [111]:
df['YearsCode'].mean()

11.662114216834588

In [112]:
# READING AND WRITING FILES WITH PANDAS

In [116]:
filt = (df['Country'] == 'United States')
us_df = df.loc[filt]
us_df.head(1)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
58,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,NaN,"Developer, back-end;Developer, desktop or ente...",28.0,19,23,Very satisfied,Very satisfied,Very confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,NaN,Yes,Office environment or company culture;Remote w...,Re-entry into the workforce,USD,United States dollar,113000.0,Weekly,2000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Non-wor...,"Less than half the time, but at least one day ...",Home,A little above average,"Yes, because I see value in code review",1.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,C#;Java;SQL,C#;F#;Java;Kotlin;SQL,Microsoft SQL Server;Oracle;SQLite,Microsoft SQL Server;Oracle;SQLite,Android;Windows,Android;Raspberry Pi;Windows,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET,Hadoop;.NET;.NET Core;Node.js;Puppet;Xamarin,Android Studio;Visual Studio,Windows,I do not use containers,NaN,NaN,Yes,Yes,Yes,I don't use social media,In real life (in person),Login,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,NaN,Easy

In [117]:
# export dataframe to a csv file:
us_df.to_csv('data/modified.csv')

In [118]:
us_df.to_csv('data/modified.tsv', sep='\t')

In [119]:
# libraries needed when working with excel : "xlwt"  "xlrd"  "openpyxl"

In [120]:
# export dataframe to excel
us_df.to_excel('data/modified.xlsx')

In [122]:
test = pd.read_excel('data/modified.xlsx', index_col='Respondent')

In [124]:
test.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
58,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,NaN,"Developer, back-end;Developer, desktop or ente...",28.0,19,23,Very satisfied,Very satisfied,Very confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,NaN,Yes,Office environment or company culture;Remote w...,Re-entry into the workforce,USD,United States dollar,113000.0,Weekly,2000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Non-wor...,"Less than half the time, but at least one day ...",Home,A little above average,"Yes, because I see value in code review",1.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,C#;Java;SQL,C#;F#;Java;Kotlin;SQL,Microsoft SQL Server;Oracle;SQLite,Microsoft SQL Server;Oracle;SQLite,Android;Windows,Android;Raspberry Pi;Windows,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET,Hadoop;.NET;.NET Core;Node.js;Puppet;Xamarin,Android Studio;Visual Studio,Windows,I do not use containers,NaN,NaN,Yes,Yes,Yes,I don't use social media,In real life (in person),Login,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,NaN,Easy
102,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","5,000 to 9,999 employees","Developer, full-stack",8.0,29,5,Slightly satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,"Something else changed (education, award, medi...",USD,United States dollar,67800.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,Average,No,NaN,"No, but I think we should",Not sure,I have some influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C;C++;Elixir;Go;Ruby;WebAssembly,Microsoft SQL Server,MongoDB;PostgreSQL;SQLite,Microsoft Azure,AWS;Kubernetes;Microsoft Azure,ASP.NET;jQuery;React.js;Other(s):,Angular/Angular.js;Vue.js,.NET;.NET Core,Node.js,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy

In [126]:
# writing to a json file
us_df.to_json('data/modified.json', orient='records', lines=True) # orient=records makes it look more readable

In [127]:
test = pd.read_json('data/modified.json', orient='records', lines=True)
test.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,None,"Developer, back-end;Developer, desktop or ente...",28.0,19,23,Very satisfied,Very satisfied,Very confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,None,Yes,Office environment or company culture;Remote w...,Re-entry into the workforce,USD,United States dollar,113000.0,Weekly,2000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Non-wor...,"Less than half the time, but at least one day ...",Home,A little above average,"Yes, because I see value in code review",1.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,C#;Java;SQL,C#;F#;Java;Kotlin;SQL,Microsoft SQL Server;Oracle;SQLite,Microsoft SQL Server;Oracle;SQLite,Android;Windows,Android;Raspberry Pi;Windows,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET,Hadoop;.NET;.NET Core;Node.js;Puppet;Xamarin,Android Studio;Visual Studio,Windows,I do not use containers,None,None,Yes,Yes,Yes,I don't use social media,In real life (in person),Login,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,None,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,None,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,None,Easy
1,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","5,000 to 9,999 employees","Developer, full-stack",8.0,29,5,Slightly satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,"Something else changed (education, award, medi...",USD,United States dollar,67800.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,Average,No,NaN,"No, but I think we should",Not sure,I have some influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C;C++;Elixir;Go;Ruby;WebAssembly,Microsoft SQL Server,MongoDB;PostgreSQL;SQLite,Microsoft Azure,AWS;Kubernetes;Microsoft Azure,ASP.NET;jQuery;React.js;Other(s):,Angular/Angular.js;Vue.js,.NET;.NET Core,Node.js,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy

In [128]:
# writing and reading with Postgres
# libraries needed: "SQLAlchemy"  "psycopg2-binary"

In [131]:
from sqlalchemy import create_engine
import psycopg2

In [132]:
engine = create_engine('postgresql://dummyUser:dummyPass@localhost:5432/dummyDB')

In [133]:
engine

Engine(postgresql://dummyUser:***@localhost:5432/dummyDB)

In [135]:
us_df.to_sql('dummy_table', engine)  # export dataframe to sql table

In [137]:
us_df.to_sql('dummy_table', engine, if_exists='replace')  # rewrite table with new data

In [139]:
sql_df = pd.read_sql('dummy_table', engine) # load sql table to dataframe

In [141]:
sql_df_query = pd.read_sql_query("select * from dummy_table where Country='United States'", engine)
# reading from sql query